"use client";

import { useState, useEffect } from "react";
import * as mammoth from "mammoth";

export interface DocumentPreviewProps {
  fileName: string;
  placeholder?: boolean;
  fileUrl?: string | null;
  fileType?: string;
  file?: File | null;
}

export function DocumentPreview({ 
  fileName, 
  placeholder = true, 
  fileUrl, 
  fileType,
  file 
}: DocumentPreviewProps) {
  const [docxHtml, setDocxHtml] = useState<string>("");
  const [isParsing, setIsParsing] = useState(false);

  // Parse .docx files when the file changes
  useEffect(() => {
    const parseDocx = async () => {
      if (!file || fileType !== "application/vnd.openxmlformats-officedocument.wordprocessingml.document") {
        setDocxHtml("");
        return;
      }

      setIsParsing(true);
      try {
        const arrayBuffer = await file.arrayBuffer();
        // mammoth.convertToHtml takes an ArrayBuffer and returns clean HTML
        const result = await mammoth.convertToHtml({ arrayBuffer });
        setDocxHtml(result.value); // The generated HTML string
      } catch (error) {
        console.error("Error parsing Word document:", error);
        setDocxHtml("<p>Error loading document preview.</p>");
      } finally {
        setIsParsing(false);
      }
    };

    parseDocx();
  }, [file, fileType]);

  const renderPreview = () => {
    console.log(fileType)
    if (isParsing) {
      return <p className="text-sm text-slate-500 animate-pulse">Parsing Word Document...</p>;
    }

    if (fileType === "application/vnd.openxmlformats-officedocument.wordprocessingml.document") {
      return (
        <div 
          className="h-[500px] w-full overflow-y-auto rounded-md bg-white p-6 text-slate-800 shadow-inner dark:bg-slate-100"
          // We safely inject the HTML generated by Mammoth
          dangerouslySetInnerHTML={{ __html: docxHtml }} 
        />
      );
    }

    if (!fileUrl) return <p className="text-sm text-slate-500">No preview available.</p>;

    if (fileType?.startsWith("image/")) {
      return (
        <img 
          src={fileUrl} 
          alt={`Preview of ${fileName}`} 
          className="max-h-[400px] w-auto object-contain rounded-md" 
        />
      );
    }

    if (fileType === "application/pdf") {
      return (
        <iframe 
          src={`${fileUrl}#toolbar=0`} 
          title={fileName}
          className="h-[500px] w-full rounded-md border-0 bg-white" 
        />
      );
    }

    if (fileType === "text/plain") {
      return (
        <iframe 
          src={`${fileUrl}#toolbar=0`} 
          title={fileName}
          className="h-[500px] w-full rounded-md border-0 bg-white" 
        />
      );
    }
    return (
      <p className="text-sm text-slate-500 dark:text-slate-400">
        Preview not available for this file type.
      </p>
    );
  };

  return (
    <div className="rounded-xl border border-slate-200 bg-slate-100/50 dark:border-slate-700 dark:bg-slate-800/50 overflow-hidden">
      <div className="border-b border-slate-200 px-4 py-2 dark:border-slate-700">
        <p className="truncate text-sm font-medium text-slate-700 dark:text-slate-300">
          {fileName}
        </p>
      </div>
      <div className="flex min-h-[240px] w-full items-center justify-center p-8">
        {placeholder ? (
          <div className="flex flex-col items-center gap-2 text-slate-400 dark:text-slate-500" aria-hidden>
            <svg className="h-12 w-12" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" strokeLinecap="round" strokeLinejoin="round">
              <path d="M14.25 10.5v5.25a2.25 2.25 0 0 1-2.25 2.25H6.75a2.25 2.25 0 0 1-2.25-2.25V10.5m9 0V4.875A2.25 2.25 0 0 0 16.875 2.625H13.5m-3 0V2.625A2.25 2.25 0 0 0 7.875 2.625H4.125A2.25 2.25 0 0 0 1.875 4.875v14.25c0 1.24 1.01 2.25 2.25 2.25h14.25c1.24 0 2.25-1.01 2.25-2.25V10.5" />
            </svg>
            <span className="text-xs">Document preview</span>
          </div>
        ) : (
          <div className="w-full h-full flex items-center justify-center">
            {renderPreview()}
          </div>
        )}
      </div>
    </div>
  );
}